document.write(typeof String(3))
document.write('\<br>')
document.write(isNaN(213))
document.write('\<br>')
document.write(isNaN('33s'))
document.write('\<br>')
document.write('<div id="no">2E310</div>')
document.write('\<br>')
document.write(-2E310)
document.write('\<br>')
document.write(Number((document.getElementById("no").innerHTML)))
document.write('\<br>')
document.write(34>231)
document.write('\<br>')
document.write(-321<231)
document.write('\<br>')
console.log(34+234)

